version: "3.8"
services:
  redis:
    image: redis:7.0-alpine
    container_name: bmad-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: bmad-qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  redis-data:
  qdrant-storage: